apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: whoami-dev-cluster
spec:
  destination:
    name: ''
    namespace: default
    server: 'https://192.168.0.35:51937'
  source:
    path: argocd
    repoURL: 'git@github.com:spreading-devops/whoami.git'
    targetRevision: HEAD
  sources: []
  project: dev-argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true