apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello-app
spec:
  destination:
    name: ''
    namespace: default
    server: 'https://192.168.0.35:51937'
  source:
    path: hello_app
    repoURL: 'git@github.com:spreading-devops/argocd-private-repo.git'
    targetRevision: HEAD
  sources: []
  project: dev-argocd
